---
- name: "Automation / Ansible / Control / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_user: "{{ lookup('env','USER') }}"
    test_group: "{{ test_user }}"
    test_home: "/home/{{ test_user }}"
    test_control: "{{ test_home }}/test_ansible64"

  tasks:
    - name: "Example: Create the directory structure for Ansible and create the site test"
      vars:
        auto_ansible_control:
          prepare: true
          setup: true
        auto_ansible_control_users:
          control:
            name: "{{ test_user }}"
            group: "{{ test_group }}"
            home: "{{ test_home }}"
        auto_ansible_control_paths:
          root: "{{ test_control }}"
          var: "{{ test_control }}"
        auto_ansible_control_site: "test"
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_ansible_control"
...
