---
- name: "Cloud / Foundry / CLI / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Foundry CLI using distro native repository"
      vars:
        cloud_foundry_cli:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.cloud.cloud_foundry_cli"
...
