---
- name: "Cloud / AWS / Realm / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: implement realm in the AWS account ACME"
      vars:
        cloud_aws_realm:
          provision: true
        cloud_aws_realm_users:
          - name: "blgmgr"
          - name: "blgadtr"
          - name: "iammgr"
          - name: "iamadtr"
          - name: "cloudmgr"
          - name: "cloudadtr"
        cloud_aws_realm_groups:
          - name: "billing_managers"
            users:
              - "blgmgr"
          - name: "billing_auditors"
            users:
              - "blgadtr"
          - name: "iam_managers"
            users:
              - "iammgr"
          - name: "iam_auditors"
            users:
              - "iamadtr"
          - name: "cloud_managers"
            users:
              - "cloudmgr"
          - name: "cloud_auditors"
            users:
              - "cloudadtr"
        cloud_aws_realm_account:
          id: "**change_me**"
          name: "**change_me**"
        cloud_aws_realm_api:
          root:
            key: "**change_me**"
            secret: "**change_me**"
      ansible.builtin.include_role:
        name: "serdigital64.cloud.cloud_aws_realm"
...
