---
- name: "Cloud / IBM / CLI / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install IBM CLI"
      vars:
        cloud_ibm_cli:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.cloud.cloud_ibm_cli"
...
