---
- name: "Database / MariaDB / Server / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: install"
      vars:
        db_mariadb_server:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.database.db_mariadb_server"
...
