---
- name: "Development / NodeJS / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install NodeJS package"
      vars:
        dev_nodejs:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_nodejs"
...
