---
- name: "Development / OpenCL / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install OpenCL package"
      vars:
        dev_opencl:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_opencl"
...
