---
- name: "Development / Tools / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Tools packages"
      vars:
        dev_tools:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_tools"
...
