---
- name: "Development / Ruby / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Ruby package"
      vars:
        dev_ruby:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_ruby"
...
