---
- name: "Development / GCC / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install GCC package"
      vars:
        dev_gcc:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_gcc"
...
