---
- name: "DevOps / Jenkins / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Jenkins, configure service, start server"
      vars:
        dops_jenkins:
          resolve_prereq: true
          deploy: true
          setup: true
          control: true
        dops_jenkins_subsystem:
          enabled: true
          status: "started"
        dops_jenkins_server_options:
          port: "8080"
          listen_address: ""
        dops_jenkins_firewall:
          zone: "public"
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_jenkins"
...
