---
- name: "DevOps / GIT / Server / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install GIT, create origin repository, create owner"
      vars:
        dops_git_server:
          resolve_prereq: true
          prepare: true
          deploy: true
          provision: true
        dops_git_server_repositories:
          - name: "test_repo"
            description: "GIT remote repository"
            public_keys: []
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_git_server"
...
