---
- name: "DevOps / YAMLLint / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: install"
      vars:
        dops_yamllint:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_yamllint"
...
