---
- name: "Hardware / GPU / AMD / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install AMD GPU drivers"
      vars:
        hw_gpu_amd:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.hardware.hw_gpu_amd"
...
