---
- name: "Infrastructure / Vagrant / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Vagrant"
      vars:
        infra_vagrant:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.infrastructure.infra_vagrant"
...
