---
- name: "Infrastructure / Terraform / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Terraform, create dedicated user, create default project repositories"
      vars:
        infra_terraform:
          resolve_prereq: true
          prepare: true
          deploy: true
          setup: true
          provision: true
        infra_terraform_projects:
          - name: "default"
        infra_terraform_paths:
          root: "/opt/terraform"
          etc: "/opt/terraform/etc"
          src: "/opt/terraform/src"
          var: "/var/opt/terraform"
        infra_terraform_users:
          terraform:
            name: "terraform"
            group: "terraform"
            home: "/home/terraform"
      ansible.builtin.include_role:
        name: "serdigital64.infrastructure.infra_terraform"
...
