---
- name: "Infrastructure / Helm / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Helm"
      vars:
        infra_helm:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.infrastructure.infra_helm"
...
