---
- name: "Monitor / Fluentd / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install Fluentd"
      vars:
        mon_fluentd:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.monitor.mon_fluentd"
...
