---
- name: "Network / IstioCtl / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install IstioCtl"
      vars:
        net_istio:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.network.net_istio"
...
