---
- name: "Storage / NFS / Client / Usage example"
  hosts: "localhost"
  gather_facts: true

  # Warning: in order for the playbook to run adjust the import definition to use an up&running NFS server
  tasks:
    - name: "Example: install nfs, configure and mount remote shares"
      vars:
        stg_nfs_client:
          resolve_prereq: true
          prepare: true
          deploy: true
          provision: true
        stg_nfs_client_imports:
          - name: "test-share"
            mount: "test-share"
            server: "nfs-serverx"
            share: "remote-share"
            options: "ro"
            mounted: "true"
      ansible.builtin.include_role:
        name: "serdigital64.storage.stg_nfs_client"
...
