---
- name: "System / Shell / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_user: "testusr64"
    test_home: "/home/testusr64"

  pre_tasks:
    - name: "Create test users"
      vars:
        sys_user:
          setup: true
        sys_user_accounts:
          - name: "{{ test_user }}"
            home: "{{ test_home }}"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_user"

  tasks:
    - name: "Example: Install unix shells bash, zsh, csh, ksh and plugins for zsh"
      vars:
        sys_shell:
          resolve_prereq: true
          deploy: true
        sys_shell_catalog:
          bash: true
          csh: true
          ksh: true
          zsh: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_shell"

    - name: "Example: Add paths to PATH, add source script, and variable declarations to user's bash profile"
      vars:
        sys_shell:
          setup: true
        sys_shell_catalog:
          bash: true
        sys_shell_users:
          - name: "{{ test_user }}"
            home: "{{ test_home }}"
            access:
              user:
                owner: "{{ test_user }}"
              group:
                owner: "{{ test_user }}"
            flavour: "bash"
            paths:
              - "/tmp/test1"
              - "/tmp/test2"
            include_system: true
            sources:
              - "/tmp/test-source-script.sh"
            variables:
              - name: "VARIABLE1"
                value: "value1"
                export: true
              - name: "VARIABLE2"
                value: "value2"
                export: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_shell"
...
