---
- name: "System / SuDo / Usage example"
  hosts: "localhost"
  gather_facts: true
  vars:
    test_user: "testusr64"

  pre_tasks:
    - name: "Create test users"
      vars:
        sys_user:
          setup: true
        sys_user_accounts:
          - name: "{{ test_user }}"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_user"

  tasks:
    - name: "Example: Add user rule to sudoers"
      vars:
        sys_sudo:
          resolve_prereq: true
          deploy: true
          setup: true
        sys_sudo_rules:
          user:
            - name: "{{ test_user }}"
              rule: "ALL=(ALL) NOPASSWD: ALL"
              present: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_sudo"
...
