---
- name: "System / Repository / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:

    - name: "Example: Install GIT tools"
      vars:
        sys_repository:
          prepare: true
          deploy: true
        sys_repository_managers:
          git: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Example: Install PIP tools"
      vars:
        sys_repository:
          prepare: true
          deploy: true
        sys_repository_managers:
          pip: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Example: Install the Snap package manager"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_managers:
          snap: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
      when:
        - ansible_distribution == 'CentOS' or
          ansible_distribution == 'OracleLinux' or
          ansible_distribution == 'Fedora'

    - name: "Example: Install the FlatPak package manager"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_managers:
          flatpak: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
      when:
        - ansible_distribution == 'Debian' or
          ansible_distribution == 'Ubuntu'

    - name: "Example: Install the Centos8 provided repository for Ansible"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_catalog_distro:
          ansible-29: true
        sys_repository_custom_distro:
          - name: "ansible-29"
            package: "centos-release-ansible-29"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
      when:
        - ansible_distribution == 'CentOS'


    - name: "Example: Install the external YUM repository for AWS CLI"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_catalog_yum:
          azure_cli: true
        sys_repository_custom_yum:
          - name: "azure_cli"
            description: "Azure CLI official RPM Repository"
            url: "https://packages.microsoft.com/yumrepos/azure-cli"
            gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
      when:
        - ansible_distribution == 'CentOS' or
          ansible_distribution == 'OracleLinux' or
          ansible_distribution == 'Fedora'

    - name: "Example: Install the external APT repository for AWS CLI"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_catalog_apt:
          azure_cli: true
        sys_repository_custom_apt:
          - name: "azure_cli"
            suite: "focal"
            component: "main"
            url: "https://packages.microsoft.com/repos/azure-cli"
            pgpkey: "https://packages.microsoft.com/keys/microsoft.asc"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
      when:
        - ansible_distribution == 'Debian' or
          ansible_distribution == 'Ubuntu'

    - name: "Example: Install the Homebrew package manager"
      vars:
        sys_repository:
          prepare: true
          deploy: true
        sys_repository_managers:
          brew: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"
...
