---
- name: "System / Kernel / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Enable IPv4 Forwarding"
      vars:
        sys_kernel:
          resolve_prereq: true
          deploy: true
          setup: true
        sys_kernel_tunables:
          net:
            ipv4:
              ip_forward: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_kernel"
...
