---
- name: "System / Fonts / Usage example"
  hosts: "localhost"
  gather_facts: true

  tasks:
    - name: "Example: Install external fonts Meslo and URW"
      vars:
        sys_fonts:
          resolve_prereq: true
          deploy: true
        sys_fonts_catalog:
          urw: true
          meslo: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_fonts"
...
